// =================================================================================
// 2. ファイル名: netlify.toml (プロジェクトのルートに配置)
//    役割: Netlifyのビルド設定とFunctionsの場所を定義します。
// =================================================================================
[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild"

// AIの応答が遅い場合に備え、関数のタイムアウトを25秒に延長します。
[functions."*"]
  timeout = 25
